name: EHSSite
favicon: null
layout_spectrum: 0.36699
typography_spectrum: 0.63606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#db4613'
    - '#fec955'
    - '#782100'
  brandStrength: 0.25
  lightness: 0.010784464422613382
  saturation: 0.24601391912437975
  rhythmicContrast: 0.4225793245714158
purpose: []
